name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        preset: [android, ios, linux-clang, linux-gcc, macos, windows]
        config: [Debug, Release]
        shared: [OFF, ON]
        lfs: [OFF, ON]
        include:
          - { os: macos-latest, preset: ios }
          - { os: macos-latest, preset: macos }
          - { os: ubuntu-latest, preset: android }
          - { os: ubuntu-latest, preset: linux-clang }
          - { os: ubuntu-latest, preset: linux-gcc }
          - { os: windows-latest, preset: windows }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .cpm
          key: zlib-1.3
          enableCrossOsArchive: true

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Configure CMake
        run: >
          cmake --preset ${{ matrix.preset }}
          -DBUILD_SHARED_LIBS=${{ matrix.shared }}
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO
          -DCPM_SOURCE_CACHE=".cpm"
          -DZLIB_ENABLE_LFS=${{ matrix.lfs }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }} --config ${{ matrix.config }}

      - name: Test
        if: contains(fromJSON('["linux-clang", "linux-gcc", "macos", "windows"]'), matrix.preset)
        run: ctest --preset ${{ matrix.preset }} -C ${{ matrix.config }}

      - name: Install
        run: cmake --build --preset ${{ matrix.preset }} --config ${{ matrix.config }} -t install
