name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [debug, release]
        type: [BUILD_SHARED_LIBS=OFF, BUILD_SHARED_LIBS=ON]
        lfs: [ZLIB_ENABLE_LFS=OFF, ZLIB_ENABLE_LFS=ON]
        include:
          - os: ubuntu-latest
            preset: linux
          - os: macos-latest
            preset: macos
          - os: windows-latest
            preset: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .cpm
          key: zlib
          enableCrossOsArchive: true

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Configure
        run: >
          cmake --preset ${{ matrix.preset }}
          -DCPM_SOURCE_CACHE=".cpm"
          -D${{ matrix.type }}
          -D${{ matrix.lfs }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}-${{ matrix.config }}

      - name: Test
        run: ctest --preset ${{ matrix.preset }}-${{ matrix.config }}

      - name: Install
        run: cmake --build --preset ${{ matrix.preset }}-${{ matrix.config }}-install
